version: "3"

services:
  web:
    build: .
    depends_on:
      - db
    volumes:
      - ./:/code
    environment:
      - DATABASE_URL=postgresql://postgres:Bright#1270@db:5433/dockert
    ports:
      - "8000:8000"
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bright#1270
      POSTGRES_DB: dockert
    ports:
      - "5432:5432"  

volumes:
  postgres_data:       